version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cleanerapplication:${TAG:-latest}
    ports:
      - "5044:8080"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - cleaner_data:/var/lib/postgresql/data/

volumes:
  cleaner_data:
